export const Users = [
  {
    "id": 1,
    "ngo_name": "Akshara Centre",
    "ngo_city": "Mumbai",
    "ngo_type": "Education",
    "profilePicture": "person/2.jpeg",
    "desc": "For the past 20 years, Akshara has worked towards a gender just society, where women can live with dignity, free from violence and discrimination. The focus is on empowering young women by imparting job skills",
    "photo": "assets/post/1.jpeg",
    "pincode":"	400059",
    "like": 0,
    "comment": 0,
  },
  {
    Ngoid: 2,
    ngo_name: "ALERT-INDIA Association for Leprosy education, Rehabilitation & Treatment India",
    ngo_city: "Mumbai",
    ngo_type: "Health",
    profilePicture: "person/2.jpeg",
    desc: "ALERT INDIA (Association for Leprosy education, Rehabilitation and Treatment-India) started working over 3 decades ago with a vision to eradicate leprosy from India",
    photo: "assets/post/1.jpeg",
    pincode:"	400037",
    like: 0,
    comment: 0,
  },
  {
    id: 3,
    ngo_name: "Annamrita-ISKCON Food Relief Foundation",
    ngo_city: "Mumbai",
    ngo_type: "Children",
    profilePicture: "person/2.jpeg",
    desc: "The organisation works on the identification, prevention, and treatment of Leprosy in communities around Mumbai suburbs and rural areas.",
    photo: "assets/post/1.jpeg",
    pincode:"	400041",
    like: 0,
    comment: 0,
  },
  {
    id: 4,
    ngo_name: "Annamrita-ISKCON Food Relief Foundation",
    ngo_city: "Mumbai",
    ngo_type: "Children",
    profilePicture: "person/2.jpeg",
    desc: "Annamrita is the strategic Mid Day Meal Programme by the government of India and run by IKSCON Food Relief Foundation, which aims to liberate the unprivileged children from malnourishment and illiteracy. For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    pincode:"	400069",
    like: 0,
    comment: 0,
  },
  {
    id: 5,
    ngo_name: "Antarang Foundation",
    ngo_city: "Mumbai",
    ngo_type: "Education",
    profilePicture: "person/2.jpeg",
    desc: "Antarang envisions a world where every young person is productively, positively and passionately engaged in a vocation of their choice.",
    photo: "assets/post/1.jpeg",
    pincode:"	400073",
    like: 0,
    comment: 0,
  },
  {
    id: 6,
    ngo_name: "Dignity Foundation",
    ngo_city: "Mumbai",
    ngo_type: "Elderly",
    profilePicture: "person/2.jpeg",
    desc: "Committed to change the way aging is perceived in India, Dignity Foundation is an NGO whose mission is to create an enlightened society in which senior citizens feel secure, confident and valued, and can live with dignity.",
    photo: "assets/post/1.jpeg",
    pincode:"	400072",
    like: 0,
    comment: 0,
  },
  {
    id: 7,
    ngo_name: "Cuddles Foundation",
    ngo_city: "Mumbai",
    ngo_type: "Health",
    profilePicture: "person/2.jpeg",
    desc: "Feed a Child. Starve Cancer.",
    photo: "assets/post/1.jpeg",
    pincode:"	400016",
    like: 0,
    comment: 0,
  },
  {
    id: 8,
    ngo_name: "Community Outreach Programme (CORP)",
    ngo_city: "Mumbai",
    ngo_type: "Education",
    profilePicture: "person/2.jpeg",
    desc: "CORP founded in 1977, now has completed 40 years. From a two teacher, 40 children initiative they have grown to become a 100 staff initiative that supports a million children and women.",
    photo: "assets/post/1.jpeg",
    pincode:"	400045",
    like: 0,
    comment: 0,

  },
  {
    id: 9,
    ngo_name: "Catalysts For Social Action",
    ngo_city: "Mumbai",
    ngo_type: "Children",
    profilePicture: "person/2.jpeg",
    desc: "Catalysts for Social Action (CSA) is a not-for-profit organization working in the arena of holistic childcare for the last 15 years. CSA’s prime areas of work are Adoption, Healthcare, and Nutrition, Hygiene, Education, Skill training and Livelihood.",
    photo: "assets/post/1.jpeg",
    pincode:"	400019",
    like: 0,
    comment: 0,
  },
  {
    id: 10,
    ngo_name: "Ashadeep Association",
    ngo_city: "Mumbai",
    ngo_type: "Children",
    profilePicture: "person/2.jpeg",
    desc: "Ashadeep Association is a charitable organization that works towards enhancing the lives of the deprived and needy single parent children, orphans, handicapped and widows. Their activities are channelized through the 7 day care centres located in the western suburbs of Mumbai.",
    photo: "assets/post/1.jpeg",
    pincode:"	400026",
    like: 0,
    comment: 0,
  }
];

